const STORE='leanMassTrackerV1';
const VERSION='1.1';
const PHOTO_DB='LeanMassPhotos';
let seed,state,selectedDate=isoToday(),mealMode='recent',currentPhotoBlob=null,calendarAnchor=isoToday();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const demoMap={
 'Goblet squat':['goblet-squat.svg','Hold a dumbbell at chest; sit hips down/back; keep heels down.'],
 'Barbell bench press':['barbell-bench-press.svg','Shoulder blades back/down, feet planted; lower under control.'],
 'One-arm dumbbell row':['one-arm-dumbbell-row.svg','Support on bench, pull elbow toward hip, avoid torso twisting.'],
 'Barbell Romanian deadlift':['romanian-deadlift.svg','Soft knees, push hips back, keep bar close and spine neutral.'],
 'Dumbbell shoulder press':['dumbbell-shoulder-press.svg','Brace abdomen and press overhead without excessive back arch.'],
 'Dumbbell curl':['dumbbell-curl.svg','Keep elbows near ribs and avoid swinging.'],
 'Bulgarian split squat':['bulgarian-split-squat.svg','Rear foot on bench, lower with control, drive through front foot.'],
 'Barbell bent-over row':['barbell-bent-over-row.svg','Hold a stable hip hinge and pull toward lower ribs.'],
 'Incline dumbbell press':['incline-dumbbell-press.svg','Use a modest incline and keep shoulders back.'],
 'Barbell/dumbbell hip thrust':['hip-thrust.svg','Upper back on bench; squeeze glutes at top without overextending.'],
 'Dumbbell lateral raise':['dumbbell-lateral-raise.svg','Use light weight; raise to shoulder height without swinging.'],
 'DB overhead triceps extension':['overhead-triceps-extension.svg','Keep upper arms still while extending the elbows.'],
 'Dumbbell reverse lunge':['reverse-lunge.svg','Step back and keep a stable shoulder-width stance.'],
 'DB curl + triceps extension':['dumbbell-curl.svg','Perform curls and triceps extensions with controlled tempo.'],
 'Plank':['plank.svg','Elbows under shoulders; squeeze abs/glutes and keep hips level.']
};
function isoToday(){const d=new Date();return iso(d)}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dateObj(s){return new Date(s+'T12:00:00')}
function fmtDate(s,opts={weekday:'short',day:'numeric',month:'short'}){return dateObj(s).toLocaleDateString(undefined,opts)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function numOrNull(x){return x===''||x==null?null:+x}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),2200)}
function targetForDate(date){const start=dateObj(state.startDate),d=dateObj(date),week=Math.max(1,Math.min(12,Math.floor((d-start)/604800000)+1));return{week,kcal:week<=2?2500:week<=4?2600:week<=8?2650:2700,protein:+state.settings.proteinTarget||105}}
function blankLog(){return{meals:[],weight:null,waist:null,chest:null,arm:null,thigh:null,sleep:null,energy:'',training:'No',workout:'Rest',workoutLog:{}}}
function logFor(date){if(!state.logs[date])state.logs[date]=blankLog();const l=state.logs[date];for(const [k,v] of Object.entries(blankLog()))if(l[k]===undefined)l[k]=v;return l}
function totals(log){return(log.meals||[]).reduce((a,m)=>({kcal:a.kcal+(+m.kcal||0),protein:a.protein+(+m.protein||0)}),{kcal:0,protein:0})}
function pct(v,t){return Math.max(0,Math.min(100,Math.round((v/t)*100)||0))}
function allMeals(){return[...(state.meals||[]),...(state.customMeals||[])]}
function latestValue(field){const es=Object.entries(state.logs).filter(([,x])=>x[field]!=null).sort(([a],[b])=>b.localeCompare(a));return es.length?+es[0][1][field]:null}
function migrate(){
 state.version=VERSION;state.customMeals=state.customMeals||[];state.favorites=state.favorites||[];state.recentMeals=state.recentMeals||[];state.reminders=state.reminders||defaultReminders();state.reminderFired=state.reminderFired||{};state.settings=state.settings||{...seed.setup};
 Object.values(state.logs||{}).forEach(l=>{for(const[k,v]of Object.entries(blankLog()))if(l[k]===undefined)l[k]=v});save();
}
function defaultReminders(){return{breakfast:{label:'Breakfast',enabled:false,time:'08:00'},lunch:{label:'Lunch',enabled:false,time:'13:00'},mass:{label:'Serious Mass',enabled:false,time:'16:00'},dinner:{label:'Dinner',enabled:false,time:'20:00'},workout:{label:'Workout',enabled:false,time:'18:30'},weigh:{label:'Weekly weigh-in',enabled:false,time:'08:00'}}}
async function boot(){
 seed=await fetch('seed-data.json',{cache:'no-store'}).then(r=>r.json());const stored=localStorage.getItem(STORE);
 if(stored){state=JSON.parse(stored);migrate()}else{state={version:VERSION,startDate:'2026-08-14',settings:{...seed.setup},meals:seed.meals,workouts:seed.workouts,logs:{},customMeals:[],favorites:[],recentMeals:[],reminders:defaultReminders(),reminderFired:{}};for(const[date,x]of Object.entries(seed.historical))state.logs[date]={...blankLog(),...x,workoutLog:{}};save()}
 setupNav();setupMealDialog();setupReminders();renderAll();checkReminders();setInterval(checkReminders,60000);
 if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(reg=>{reg.update();if(reg.waiting)showUpdateBanner(reg)}).catch(()=>{});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!sessionStorage.getItem('reloaded11')){sessionStorage.setItem('reloaded11','1');location.reload()}})}
}
function showUpdateBanner(reg){const host=$('.view.active');if(!host)return;host.insertAdjacentHTML('afterbegin',`<div class="update-banner">A new app version is ready. <button class="small-btn" id="applyUpdate">Refresh now</button></div>`);$('#applyUpdate').onclick=()=>reg.waiting.postMessage({type:'SKIP_WAITING'})}
function setupNav(){ $$('.bottom-nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#todayBtn').onclick=()=>{selectedDate=isoToday();calendarAnchor=selectedDate;showView('today')};$('#bellBtn').onclick=()=>openReminderDialog() }
function showView(name){$$('.view').forEach(v=>v.classList.remove('active'));$(`#view-${name}`).classList.add('active');$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));renderAll()}
function renderAll(){renderToday();renderMeals();renderWorkouts();renderProgress();renderSettings();hydratePhotos()}
function workoutSuggestion(date){const d=dateObj(date).getDay();return({1:'Workout A · preferred',3:'Workout B · preferred',6:'Workout C · preferred',5:'Make-up option · A or C',0:'Make-up option · B or C'}[d]||'Recovery / rest day')}
function statusForDay(date){const l=state.logs[date];if(!l)return'';return(l.meals?.length||l.weight!=null||l.training==='Yes')?'●':''}
function weekDates(anchor){const d=dateObj(anchor),dow=(d.getDay()+6)%7,m=new Date(d);m.setDate(d.getDate()-dow);return Array.from({length:7},(_,i)=>{const x=new Date(m);x.setDate(m.getDate()+i);return iso(x)})}
function shiftWeek(n){const d=dateObj(calendarAnchor);d.setDate(d.getDate()+7*n);calendarAnchor=iso(d);renderToday();hydratePhotos()}
function renderWeekCalendar(){const days=weekDates(calendarAnchor);return`<div class="card"><div class="calendar-head"><button class="ghost" onclick="shiftWeek(-1)">‹</button><div><div class="muted">Weekly calendar</div><div class="month-title">${fmtDate(days[0],{month:'long',year:'numeric'})}</div></div><button class="ghost" onclick="shiftWeek(1)">›</button></div><div class="week-grid">${days.map(d=>`<button class="day-cell ${d===selectedDate?'selected':''}" onclick="selectedDate='${d}';calendarAnchor='${d}';renderAll()"><small>${fmtDate(d,{weekday:'short'})}</small><strong>${dateObj(d).getDate()}</strong><div class="dots">${statusForDay(d)?'<span class="day-dot"></span>':''}</div></button>`).join('')}</div>${weeklySummary(days)}</div>`}
function weeklySummary(days){let kcal=0,prot=0,n=0,w=0;days.forEach(d=>{const l=state.logs[d];if(l){const t=totals(l);if(t.kcal){kcal+=t.kcal;prot+=t.protein;n++}if(l.training==='Yes')w++}});return`<div class="weekly-summary"><div><span class="muted">Avg kcal</span><b>${n?Math.round(kcal/n):'—'}</b></div><div><span class="muted">Avg protein</span><b>${n?Math.round(prot/n)+' g':'—'}</b></div><div><span class="muted">Workouts</span><b>${w}/3</b></div></div>`}
function renderToday(){
 const log=logFor(selectedDate),t=targetForDate(selectedDate),sum=totals(log),weight=latestValue('weight'),gain=weight==null?0:weight-state.settings.startWeight,status=sum.kcal>=t.kcal*.9&&sum.protein>=t.protein?'On track':sum.kcal>t.kcal*1.15?'Above target':'Building';
 const mealHtml=log.meals.length?log.meals.map((m,i)=>`<div class="meal-row row between"><div class="meal-main">${m.photoId?`<img class="meal-thumb photo-ref" data-photo="${esc(m.photoId)}">`:''}<div><span class="pill">${esc(m.slot)}</span><strong>${esc(m.name)}</strong><span class="muted">${Math.round(m.kcal)} kcal · ${(+m.protein).toFixed((+m.protein)%1?1:0)} g protein</span></div></div><button class="ghost tiny" onclick="deleteMeal('${selectedDate}',${i})">Delete</button></div>`).join(''):`<div class="empty">No meals logged yet.</div>`;
 $('#view-today').innerHTML=`${renderWeekCalendar()}<div class="card hero"><div class="row between"><div><div class="eyebrow">WEEK ${t.week} · ${fmtDate(selectedDate)}</div><h2>${status}</h2><div class="muted">Goal: ${state.settings.startWeight} → ${state.settings.goalWeight} kg</div></div><div class="right"><div class="big">${weight==null?'—':weight.toFixed(1)} kg</div><div class="muted">${weight==null?'No weigh-in yet':`${gain>=0?'+':''}${gain.toFixed(1)} kg from start`}</div></div></div></div>
 <div class="kpis"><div class="kpi"><span class="muted">Calories</span><div class="big">${Math.round(sum.kcal)}</div><div class="muted">of ${t.kcal} kcal</div><div class="progress"><i style="width:${pct(sum.kcal,t.kcal)}%"></i></div></div><div class="kpi"><span class="muted">Protein</span><div class="big">${Math.round(sum.protein)}g</div><div class="muted">of ${t.protein} g</div><div class="progress"><i style="width:${pct(sum.protein,t.protein)}%"></i></div></div></div>
 <div class="card"><div class="section-title"><div><span class="muted">Selected day</span><h2>${fmtDate(selectedDate)}</h2></div><input id="datePick" type="date" value="${selectedDate}" style="width:auto;margin:0"></div><div class="quick-grid"><button class="quick" onclick="openMeal('Breakfast')"><strong>☀︎ Breakfast</strong><span class="muted">Log meal</span></button><button class="quick" onclick="openMeal('Snack 1')"><strong>◉ Snack</strong><span class="muted">Log snack</span></button><button class="quick" onclick="openMeal('Lunch')"><strong>♨ Lunch</strong><span class="muted">Log meal</span></button><button class="quick" onclick="openMeal('Dinner')"><strong>◒ Dinner</strong><span class="muted">Log meal</span></button><button class="quick" onclick="quickMass()"><strong>＋ Serious Mass</strong><span class="muted">631 kcal · 25g</span></button></div></div>
 <div class="card"><div class="row between"><h3>Meals</h3><button class="ghost" onclick="openMeal('Other')">+ Add</button></div>${mealHtml}<div class="metricline"><span>Total</span><b>${Math.round(sum.kcal)} kcal · ${Math.round(sum.protein)} g</b></div></div>
 <div class="card"><h3>Daily check-in</h3><div class="two-col"><label>Weight (kg)<input id="todayWeight" type="number" step="0.1" value="${log.weight??''}"></label><label>Sleep (hours)<input id="todaySleep" type="number" step="0.1" value="${log.sleep??''}"></label><label>Waist (cm)<input id="todayWaist" type="number" step="0.1" value="${log.waist??''}"></label><label>Chest (cm)<input id="todayChest" type="number" step="0.1" value="${log.chest??''}"></label><label>Upper arm (cm)<input id="todayArm" type="number" step="0.1" value="${log.arm??''}"></label><label>Thigh (cm)<input id="todayThigh" type="number" step="0.1" value="${log.thigh??''}"></label><label>Energy<select id="todayEnergy"><option></option>${['Low','Moderate','Good','High'].map(x=>`<option ${log.energy===x?'selected':''}>${x}</option>`).join('')}</select></label></div><button class="primary" onclick="saveCheckin()">Save check-in</button></div>
 <div class="card"><span class="muted">Workout</span><h3>${workoutSuggestion(selectedDate)}</h3><p class="muted">Target remains 3 resistance sessions/week. Friday evening and Sunday are make-up alternatives, not extra compulsory lifting days.</p><button class="primary" onclick="showView('workouts')">Open workout</button></div>`;
 $('#datePick').onchange=e=>{selectedDate=e.target.value;calendarAnchor=selectedDate;renderAll()};
}
function saveCheckin(){const l=logFor(selectedDate);l.weight=numOrNull($('#todayWeight').value);l.sleep=numOrNull($('#todaySleep').value);l.waist=numOrNull($('#todayWaist').value);l.chest=numOrNull($('#todayChest').value);l.arm=numOrNull($('#todayArm').value);l.thigh=numOrNull($('#todayThigh').value);l.energy=$('#todayEnergy').value;save();renderAll();toast('Check-in saved')}
function quickMass(){logFor(selectedDate).meals.push({slot:'Snack 2',name:'Serious Mass - 1 scoop',kcal:631,protein:25,notes:'168 g'});rememberMeal('Serious Mass - 1 scoop');save();renderAll();toast('Serious Mass added')}

function setupMealDialog(){
 $('#mealSearch').oninput=()=>populateMealSelect($('#mealSearch').value);$('#mealSelect').onchange=syncMealFields;$('#mealPortion').onchange=syncMealFields;$('#mealPhoto').onchange=previewPhoto;$('#saveMeal').onclick=saveMealEntry;$('#favMealBtn').onclick=toggleCurrentFavorite;$('#seriousMassBtn').onclick=()=>{$('#mealSearch').value='Serious Mass - 1 scoop';populateMealSelect('Serious Mass - 1 scoop')};$$('#mealMode button').forEach(b=>b.onclick=()=>{mealMode=b.dataset.mode;$$('#mealMode button').forEach(x=>x.classList.toggle('active',x===b));populateMealSelect($('#mealSearch').value)})
}
function filteredMeals(q=''){let list=allMeals(),q2=q.toLowerCase();if(q2)list=list.filter(m=>m.name.toLowerCase().includes(q2));if(mealMode==='favorites')list=list.filter(m=>state.favorites.includes(m.name));if(mealMode==='recent'&&!q2){const by=new Map(allMeals().map(m=>[m.name,m]));list=state.recentMeals.map(n=>by.get(n)).filter(Boolean);if(!list.length)list=allMeals().slice(0,20)}return list.slice(0,120)}
function openMeal(slot='Other'){currentPhotoBlob=null;$('#mealSlot').value=slot;$('#mealSearch').value='';$('#mealPortion').value='1';$('#mealNotes').value='';$('#mealPhoto').value='';$('#photoPreview').classList.add('hidden');populateMealSelect('');$('#mealDialog').showModal()}
function populateMealSelect(q=''){const list=filteredMeals(q);$('#mealSelect').innerHTML=list.map(m=>`<option value="${esc(m.name)}">${esc(m.name)} · ${Math.round(m.kcal)} kcal / ${m.protein}g</option>`).join('')+`<option value="__manual__">Other / manual entry</option>`;syncMealFields()}
function syncMealFields(){const v=$('#mealSelect').value,m=allMeals().find(x=>x.name===v),portion=+$('#mealPortion').value||1;if(m){$('#mealKcal').value=Math.round(m.kcal*portion);$('#mealProtein').value=Math.round(m.protein*portion*10)/10;$('#mealNotes').placeholder=m.notes||'optional'}else{$('#mealKcal').value='';$('#mealProtein').value='';$('#mealNotes').placeholder='Describe the meal'}$('#favMealBtn').textContent=state.favorites.includes(v)?'★ Favourite':'☆ Favourite'}
function toggleCurrentFavorite(){const n=$('#mealSelect').value;if(!n||n==='__manual__')return;const i=state.favorites.indexOf(n);if(i>=0)state.favorites.splice(i,1);else state.favorites.unshift(n);save();syncMealFields();toast(i>=0?'Removed from favourites':'Added to favourites')}
function rememberMeal(name){state.recentMeals=[name,...state.recentMeals.filter(x=>x!==name)].slice(0,15)}
async function previewPhoto(e){const f=e.target.files?.[0];if(!f)return;currentPhotoBlob=await compressImage(f);const u=URL.createObjectURL(currentPhotoBlob);const p=$('#photoPreview');p.style.backgroundImage=`url(${u})`;p.classList.remove('hidden')}
async function saveMealEntry(){const sel=$('#mealSelect').value,name=sel==='__manual__'?($('#mealNotes').value.trim()||'Custom / manual meal'):sel,kcal=+$(`#mealKcal`).value||0,protein=+$(`#mealProtein`).value||0;let photoId=null;if(currentPhotoBlob){photoId=crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();await putPhoto(photoId,currentPhotoBlob)}logFor(selectedDate).meals.push({slot:$('#mealSlot').value,name,kcal,protein,notes:$('#mealNotes').value,photoId});rememberMeal(name);save();$('#mealDialog').close();renderAll();toast('Meal added')}
async function deleteMeal(date,i){const l=logFor(date),m=l.meals[i];if(m?.photoId)await deletePhoto(m.photoId);l.meals.splice(i,1);save();renderAll()}

function renderMeals(){
 $('#view-meals').innerHTML=`<div class="section-title"><div><span class="muted">Your food library</span><h2>Meals</h2></div><span class="pill blue">${allMeals().length} foods</span></div><div class="card"><div class="segmented"><button class="active" onclick="mealLibraryMode('all',this)">All</button><button onclick="mealLibraryMode('favorites',this)">Favourites</button><button onclick="mealLibraryMode('recent',this)">Recent</button></div><label>Search<input id="dbSearch" type="search" placeholder="Rice, yam, yoghurt, Serious Mass…"></label><div id="dbList"></div></div><div class="card"><h3>Create custom food</h3><div class="two-col"><label>Name<input id="customName"></label><label>Calories<input id="customKcal" type="number"></label><label>Protein (g)<input id="customProtein" type="number" step="0.5"></label><label>Notes<input id="customNotes"></label></div><button class="primary" onclick="addCustomMeal()">Save food</button></div>`;state.libraryMode=state.libraryMode||'all';const renderList=()=>{const q=$('#dbSearch').value.toLowerCase();let items=allMeals().filter(m=>m.name.toLowerCase().includes(q));if(state.libraryMode==='favorites')items=items.filter(m=>state.favorites.includes(m.name));if(state.libraryMode==='recent'){const mp=new Map(items.map(m=>[m.name,m]));items=state.recentMeals.map(n=>mp.get(n)).filter(Boolean)}$('#dbList').innerHTML=items.slice(0,70).map(m=>`<div class="meal-row row between"><div><strong>${esc(m.name)}</strong><span class="muted">${Math.round(m.kcal)} kcal · ${m.protein} g protein</span>${m.notes?`<div class="tiny muted">${esc(m.notes)}</div>`:''}</div><button class="small-btn ${state.favorites.includes(m.name)?'favourite':''}" onclick="toggleFavoriteName('${encodeURIComponent(m.name)}')">${state.favorites.includes(m.name)?'★':'☆'}</button></div>`).join('')||'<div class="empty">No match</div>'};state.renderDbList=renderList;$('#dbSearch').oninput=renderList;renderList()}
function mealLibraryMode(m,b){state.libraryMode=m;save();b.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));state.renderDbList?.()}
function toggleFavoriteName(encoded){const n=decodeURIComponent(encoded),i=state.favorites.indexOf(n);if(i>=0)state.favorites.splice(i,1);else state.favorites.unshift(n);save();renderMeals()}
function addCustomMeal(){const name=$('#customName').value.trim();if(!name)return;state.customMeals.push({name,kcal:+$('#customKcal').value||0,protein:+$('#customProtein').value||0,notes:$('#customNotes').value||'Custom'});save();renderMeals();toast('Custom food saved')}

function renderWorkouts(){const buttons=['A','B','C'].map(k=>`<button class="chip ${(state.uiWorkout||'A')===k?'active':''}" onclick="state.uiWorkout='${k}';renderWorkouts();hydratePhotos()">Workout ${k}</button>`).join(''),k=state.uiWorkout||'A',flex=seed.flex[k],ex=state.workouts[k],log=logFor(selectedDate);$('#view-workouts').innerHTML=`<div class="section-title"><div><span class="muted">Home programme</span><h2>Workout ${k}</h2></div><span class="pill">3 / week</span></div><div class="notice success"><b>Flexible:</b> preferred ${flex.preferred}; alternative ${flex.alternative}. Use make-up days when work fatigue causes a miss.</div><div class="tabbar">${buttons}</div><div class="card"><div class="row between"><div><span class="muted">${fmtDate(selectedDate)}</span><h3>Workout ${k}</h3></div><button class="ghost" onclick="selectedDate=isoToday();renderAll()">Today</button></div>${ex.map((x,i)=>exerciseHtml(k,x,i,log)).join('')}<button class="primary" onclick="completeWorkout('${k}')">Mark Workout ${k} complete</button></div><div class="notice">The demo graphics are schematic cues, not a substitute for an in-person coach. Stop if an exercise causes sharp pain, dizziness or unusual symptoms.</div>`}
function exerciseHtml(k,x,i,log){const key=`${k}-${i}`,v=log.workoutLog?.[key]||{},demo=demoMap[x.exercise];return`<div class="exercise-row"><div class="row between"><div><strong>${esc(x.exercise)}</strong><div class="muted">${x.sets} sets · ${esc(x.reps)}</div></div><button class="ghost tiny" onclick="openDemo('${encodeURIComponent(x.exercise)}')">Demo</button></div>${x.note?`<div class="tiny muted">${esc(x.note)}</div>`:''}<div class="set-grid"><label>Load kg<input type="number" step="0.5" id="load-${key}" value="${v.load??''}"></label><label>Last reps<input type="number" id="reps-${key}" value="${v.reps??''}"></label><button class="ghost" onclick="saveExercise('${key}')">Save</button></div></div>`}
function openDemo(encoded){const name=decodeURIComponent(encoded),d=demoMap[name]||['goblet-squat.svg','Use controlled form.'];$('#demoBody').innerHTML=`<div class="dialog-head"><button class="text-btn" onclick="$('#demoDialog').close()">Close</button><h3>${esc(name)}</h3><span></span></div><img class="exercise-demo" src="demos/${d[0]}" alt="${esc(name)} form guide"><div class="demo-cue"><b>Key cue</b><div class="muted">${esc(d[1])}</div></div><p class="footer-note">These are simplified visual reminders. Start with manageable loads and prioritize control and comfort.</p>`;$('#demoDialog').showModal()}
function saveExercise(key){const l=logFor(selectedDate);l.workoutLog=l.workoutLog||{};l.workoutLog[key]={load:numOrNull($(`#load-${key}`).value),reps:numOrNull($(`#reps-${key}`).value)};save();toast('Exercise saved')}
function completeWorkout(k){const l=logFor(selectedDate);l.training='Yes';l.workout=k;save();renderAll();toast(`Workout ${k} completed`)}

function renderProgress(){const entries=Object.entries(state.logs).sort(([a],[b])=>a.localeCompare(b)),weigh=entries.filter(([,x])=>x.weight!=null),latest=latestValue('weight'),goal=state.settings.goalWeight,start=state.settings.startWeight,week=weekDates(selectedDate);let kcal=0,prot=0,n=0;week.forEach(d=>{const t=totals(state.logs[d]||{meals:[]});if(t.kcal){kcal+=t.kcal;prot+=t.protein;n++}});$('#view-progress').innerHTML=`<div class="section-title"><div><span class="muted">12-week trajectory</span><h2>Progress</h2></div></div><div class="stat3"><div class="kpi"><span class="muted">Latest</span><div class="big">${latest??'—'}</div><div class="muted">kg</div></div><div class="kpi"><span class="muted">Goal</span><div class="big">${goal}</div><div class="muted">kg</div></div><div class="kpi"><span class="muted">Logged</span><div class="big">${weigh.length}</div><div class="muted">weights</div></div></div><div class="card"><h3>Weight trend</h3><div class="canvas-wrap"><canvas id="weightChart" width="760" height="320"></canvas></div><div class="muted">Target path: ${start} → ${goal} kg across 12 weeks.</div></div><div class="card"><h3>Body measurements</h3><div class="body-metrics">${['waist','chest','arm','thigh'].map(f=>metricCard(f)).join('')}</div><div class="canvas-wrap"><canvas id="bodyChart" width="760" height="320"></canvas></div></div><div class="card"><h3>This week</h3><div class="weekly-summary"><div><span class="muted">Avg calories</span><b>${n?Math.round(kcal/n):'—'}</b></div><div><span class="muted">Avg protein</span><b>${n?Math.round(prot/n)+'g':'—'}</b></div><div><span class="muted">Workouts</span><b>${week.filter(d=>state.logs[d]?.training==='Yes').length}/3</b></div></div></div><div class="card"><h3>Meal photos</h3><div id="photoGallery" class="photo-gallery"><div class="empty">Loading photos…</div></div></div><div class="card"><h3>Recent check-ins</h3>${entries.slice(-12).reverse().map(([d,x])=>`<div class="history-row row between"><div><strong>${fmtDate(d)}</strong><div class="muted">${x.energy||'No energy rating'} · ${x.sleep??'—'} h sleep</div></div><div class="right"><b>${x.weight??'—'} kg</b><div class="muted">${Math.round(totals(x).kcal)} kcal</div></div></div>`).join('')||'<div class="empty">No logs yet</div>'}</div>`;requestAnimationFrame(()=>{drawWeightChart();drawBodyChart();renderPhotoGallery()})}
function metricCard(f){const label={waist:'Waist',chest:'Chest',arm:'Upper arm',thigh:'Thigh'}[f],v=latestValue(f);return`<div class="body-metric"><span class="muted">${label}</span><b>${v==null?'—':v.toFixed(1)}</b><span class="muted">cm</span></div>`}
function drawWeightChart(){const c=$('#weightChart');if(!c)return;const ctx=c.getContext('2d'),W=c.width,H=c.height,p=44,startD=dateObj(state.startDate),end=new Date(startD.getTime()+83*86400000),weights=Object.entries(state.logs).filter(([,x])=>x.weight!=null).sort(([a],[b])=>a.localeCompare(b)),min=Math.min(61,state.settings.startWeight-2,...weights.map(x=>x[1].weight)),max=Math.max(70,state.settings.goalWeight+2,...weights.map(x=>x[1].weight)),x=d=>p+((dateObj(d)-startD)/(end-startD))*(W-2*p),y=v=>H-p-((v-min)/(max-min))*(H-2*p);ctx.clearRect(0,0,W,H);ctx.font='12px -apple-system';for(let v=Math.ceil(min);v<=max;v++){ctx.strokeStyle='#e3e8ee';ctx.beginPath();ctx.moveTo(p,y(v));ctx.lineTo(W-p,y(v));ctx.stroke();ctx.fillStyle='#7b8790';ctx.fillText(v,10,y(v)+4)}ctx.strokeStyle='#aab7c2';ctx.setLineDash([7,7]);ctx.beginPath();ctx.moveTo(p,y(state.settings.startWeight));ctx.lineTo(W-p,y(state.settings.goalWeight));ctx.stroke();ctx.setLineDash([]);if(weights.length){ctx.strokeStyle='#0a64d8';ctx.lineWidth=4;ctx.beginPath();weights.forEach(([d,l],i)=>i?ctx.lineTo(x(d),y(l.weight)):ctx.moveTo(x(d),y(l.weight)));ctx.stroke();weights.forEach(([d,l])=>{ctx.fillStyle='#103d61';ctx.beginPath();ctx.arc(x(d),y(l.weight),5,0,Math.PI*2);ctx.fill()})}}
function drawBodyChart(){const c=$('#bodyChart');if(!c)return;const ctx=c.getContext('2d'),W=c.width,H=c.height,p=44,fields=['waist','chest','arm','thigh'],colors=['#0a64d8','#35ad70','#e58a23','#7959c7'],entries=Object.entries(state.logs).sort(([a],[b])=>a.localeCompare(b)),vals=[];entries.forEach(([,l])=>fields.forEach(f=>{if(l[f]!=null)vals.push(+l[f])}));ctx.clearRect(0,0,W,H);if(!vals.length){ctx.fillStyle='#7b8790';ctx.font='16px -apple-system';ctx.fillText('Add waist, chest, arm or thigh measurements to see trends.',30,80);return}const min=Math.max(0,Math.min(...vals)-4),max=Math.max(...vals)+4,start=dateObj(state.startDate),end=new Date(start.getTime()+83*86400000),x=d=>p+((dateObj(d)-start)/(end-start))*(W-2*p),y=v=>H-p-((v-min)/(max-min))*(H-2*p);fields.forEach((f,fi)=>{const pts=entries.filter(([,l])=>l[f]!=null);if(!pts.length)return;ctx.strokeStyle=colors[fi];ctx.lineWidth=3;ctx.beginPath();pts.forEach(([d,l],i)=>i?ctx.lineTo(x(d),y(l[f])):ctx.moveTo(x(d),y(l[f])));ctx.stroke();ctx.fillStyle=colors[fi];ctx.font='12px -apple-system';ctx.fillText({waist:'Waist',chest:'Chest',arm:'Arm',thigh:'Thigh'}[f],50+fi*115,22)})}

function renderSettings(){const s=state.settings;$('#view-settings').innerHTML=`<div class="section-title"><div><span class="muted">V1.1</span><h2>More</h2></div></div><div class="card"><h3>Targets</h3><div class="two-col"><label>Starting weight<input id="setStart" type="number" step="0.1" value="${s.startWeight}"></label><label>Goal weight<input id="setGoal" type="number" step="0.1" value="${s.goalWeight}"></label><label>Protein target<input id="setProtein" type="number" value="${s.proteinTarget}"></label><label>Programme start<input id="setDate" type="date" value="${state.startDate}"></label></div><button class="primary" onclick="saveSettings()">Save targets</button></div><div class="card"><div class="row between"><h3>Reminders</h3><button class="ghost" onclick="openReminderDialog()">Configure</button></div><p class="muted">Meal, Serious Mass, workout and weigh-in reminders. Notifications require permission.</p><button class="secondary" onclick="requestNotifications()">Enable notifications</button></div><div class="card"><h3>Serious Mass</h3><div class="metricline"><span>1 heaped scoop</span><b>631 kcal · 25 g</b></div><div class="muted">168 g powder; approximately 124 g carbohydrate and 1.5 g creatine.</div></div><div class="card"><h3>Backup & restore</h3><p class="muted">Export includes logs, settings, custom foods and meal photos. Keep a periodic backup outside Safari.</p><div class="actions"><button class="primary" onclick="exportBackup()">Export backup</button><label class="secondary" style="text-align:center;cursor:pointer">Import backup<input type="file" accept="application/json" hidden onchange="importBackup(this.files[0])"></label></div></div><div class="card"><h3>About V1.1</h3><p class="muted">Meal photos, favourites/recent meals, portion adjustment, Serious Mass quick-add, flexible weekly calendar, exercise demo guides, body charts, reminders, improved backup and a refreshed iPhone-style interface.</p><p class="footer-note">Reminder limitation: GitHub Pages has no notification server. V1.1 can notify while the app is active/recently opened and checks overdue reminders when reopened, but reliable background push while fully closed requires a later server-backed push service.</p></div><div class="card"><button class="secondary danger" onclick="resetApp()">Reset app data</button></div>`}
function saveSettings(){state.settings.startWeight=+$('#setStart').value;state.settings.goalWeight=+$('#setGoal').value;state.settings.proteinTarget=+$('#setProtein').value;state.startDate=$('#setDate').value;save();renderAll();toast('Targets saved')}

function setupReminders(){}
function openReminderDialog(){const r=state.reminders;$('#reminderBody').innerHTML=`<div class="dialog-head"><button class="text-btn" onclick="$('#reminderDialog').close()">Done</button><h3>Reminders</h3><button class="text-btn" onclick="requestNotifications()">Allow</button></div><p class="muted">Choose times. Workout reminder fires on Mon/Wed/Sat and make-up awareness on Fri/Sun; weigh-in reminder is Sunday.</p>${Object.entries(r).map(([k,v])=>`<div class="reminder-row"><div><b>${esc(v.label)}</b><input type="time" id="rt-${k}" value="${v.time}" onchange="updateReminder('${k}')"></div><input class="toggle" id="re-${k}" type="checkbox" ${v.enabled?'checked':''} onchange="updateReminder('${k}')"></div>`).join('')}<div class="actions"><button class="secondary" onclick="testNotification()">Test notification</button></div>`;$('#reminderDialog').showModal()}
function updateReminder(k){state.reminders[k].time=$(`#rt-${k}`).value;state.reminders[k].enabled=$(`#re-${k}`).checked;save()}
async function requestNotifications(){if(!('Notification'in window)){toast('Notifications are not supported here');return}const p=await Notification.requestPermission();toast(p==='granted'?'Notifications enabled':'Notification permission not granted')}
function dueForReminder(k,date){const day=dateObj(date).getDay();if(k==='workout')return[1,3,5,6,0].includes(day);if(k==='weigh')return day===0;return true}
async function testNotification(){if(Notification.permission!=='granted')await requestNotifications();if(Notification.permission==='granted')showNotification('Lean Mass Tracker','This is a test reminder.')}
function showNotification(title,body){if(navigator.serviceWorker?.controller){navigator.serviceWorker.ready.then(r=>r.showNotification(title,{body,icon:'icons/icon-192.png',badge:'icons/icon-192.png'}))}else if(Notification.permission==='granted')new Notification(title,{body})}
function checkReminders(){if(!state?.reminders||!('Notification' in window)||Notification.permission!=='granted')return;const now=new Date(),today=isoToday(),hm=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`;for(const[k,r]of Object.entries(state.reminders)){if(!r.enabled||!dueForReminder(k,today))continue;const firedKey=`${today}-${k}`;if(state.reminderFired[firedKey])continue;const [h,m]=r.time.split(':').map(Number),target=new Date();target.setHours(h,m,0,0);const diff=(now-target)/60000;if(diff>=0&&diff<=90){showNotification('Lean Mass Tracker',`${r.label} reminder · ${r.time}`);state.reminderFired[firedKey]=Date.now();save()}}}

async function openPhotoDB(){return new Promise((res,rej)=>{const req=indexedDB.open(PHOTO_DB,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('photos'))req.result.createObjectStore('photos')};req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}
async function putPhoto(id,blob){const db=await openPhotoDB();return new Promise((res,rej)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').put(blob,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function getPhoto(id){const db=await openPhotoDB();return new Promise((res,rej)=>{const r=db.transaction('photos').objectStore('photos').get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function deletePhoto(id){const db=await openPhotoDB();return new Promise(res=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').delete(id);tx.oncomplete=res})}
async function allPhotoRecords(){const ids=[];Object.values(state.logs).forEach(l=>(l.meals||[]).forEach(m=>{if(m.photoId)ids.push(m.photoId)}));const out={};for(const id of [...new Set(ids)]){const b=await getPhoto(id);if(b)out[id]=b}return out}
async function hydratePhotos(){for(const img of $$('.photo-ref')){const b=await getPhoto(img.dataset.photo);if(b)img.src=URL.createObjectURL(b)}}
async function renderPhotoGallery(){const host=$('#photoGallery');if(!host)return;const refs=[];Object.entries(state.logs).sort(([a],[b])=>b.localeCompare(a)).forEach(([d,l])=>(l.meals||[]).forEach(m=>{if(m.photoId)refs.push({id:m.photoId,date:d,name:m.name})}));if(!refs.length){host.innerHTML='<div class="empty">No meal photos yet.</div>';return}host.innerHTML=refs.slice(0,15).map(r=>`<img class="gallery-img photo-ref" data-photo="${r.id}" title="${esc(r.name)} · ${fmtDate(r.date)}">`).join('');hydratePhotos()}
function compressImage(file){return new Promise((res,rej)=>{const im=new Image(),u=URL.createObjectURL(file);im.onload=()=>{const max=1200,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);c.toBlob(b=>{URL.revokeObjectURL(u);b?res(b):rej(new Error('Photo compression failed'))},'image/jpeg',.72)};im.onerror=rej;im.src=u})}
function blobToDataURL(blob){return new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(blob)})}
function dataURLToBlob(s){const [h,b64]=s.split(','),mime=h.match(/:(.*?);/)[1],bin=atob(b64),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return new Blob([arr],{type:mime})}
async function exportBackup(){const photos=await allPhotoRecords(),encoded={};for(const[id,b]of Object.entries(photos))encoded[id]=await blobToDataURL(b);const pack={app:'Lean Mass Tracker',version:VERSION,exportedAt:new Date().toISOString(),state,photos:encoded},blob=new Blob([JSON.stringify(pack)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`lean-mass-v1-1-backup-${isoToday()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);toast('Backup exported')}
function importBackup(file){if(!file)return;const r=new FileReader();r.onload=async()=>{try{const pack=JSON.parse(r.result);state=pack.state||pack;migrate();if(pack.photos)for(const[id,data]of Object.entries(pack.photos))await putPhoto(id,dataURLToBlob(data));save();renderAll();toast('Backup restored')}catch(e){alert('That backup could not be restored.')}};r.readAsText(file)}
function resetApp(){if(confirm('Reset all app data back to the starter tracker?')){localStorage.removeItem(STORE);indexedDB.deleteDatabase(PHOTO_DB);location.reload()}}

window.openMeal=openMeal;window.deleteMeal=deleteMeal;window.saveCheckin=saveCheckin;window.quickMass=quickMass;window.showView=showView;window.shiftWeek=shiftWeek;window.renderMeals=renderMeals;window.mealLibraryMode=mealLibraryMode;window.toggleFavoriteName=toggleFavoriteName;window.addCustomMeal=addCustomMeal;window.renderWorkouts=renderWorkouts;window.openDemo=openDemo;window.saveExercise=saveExercise;window.completeWorkout=completeWorkout;window.saveSettings=saveSettings;window.openReminderDialog=openReminderDialog;window.updateReminder=updateReminder;window.requestNotifications=requestNotifications;window.testNotification=testNotification;window.exportBackup=exportBackup;window.importBackup=importBackup;window.resetApp=resetApp;
boot();
